PACKAGE_NAME="ch9344"
PACKAGE_VERSION="2.3.1"
BUILT_MODULE_NAME[0]="ch9344"
DEST_MODULE_LOCATION[0]="/updates/dkms"
AUTOINSTALL="yes"
MAKE[0]="make KERNELRELEASE=${kernelver}"
CLEAN="make KERNELRELEASE=${kernelver} clean"
